/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'case-studies': CaseStudy;
    categories: Category;
    reviews: Review;
    media: Media;
    leads: Lead;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Client success stories. Affiliate case studies show metrics + narrative; influencer case studies also support campaign videos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Headline of the case study, e.g. "How X scaled to $60K in 4 months".
   */
  title: string;
  /**
   * URL identifier — leave blank to auto-generate from the title.
   */
  slug?: string | null;
  type: 'affiliate' | 'influencer';
  category?: (number | null) | Category;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  client?: string | null;
  industry?: string | null;
  /**
   * e.g. Awin, Impact.com, ADCELL, Daisycon
   */
  network?: string | null;
  /**
   * e.g. "6 Months (Nov 2025 – Apr 2026)"
   */
  duration?: string | null;
  /**
   * Influencer campaign details.
   */
  influencer?: {
    /**
     * e.g. @skincare.ninja
     */
    handle?: string | null;
    platform?: ('instagram' | 'tiktok' | 'youtube') | null;
    /**
     * e.g. 101K
     */
    followers?: string | null;
    /**
     * e.g. Abib
     */
    brandPartner?: string | null;
    /**
     * Brand website (optional)
     */
    brandUrl?: string | null;
  };
  /**
   * Headline numbers shown in the results band, e.g. Revenue / $23,966 / +130%.
   */
  metrics?:
    | {
        label: string;
        value: string;
        /**
         * e.g. +130.45% (optional)
         */
        change?: string | null;
        id?: string | null;
      }[]
    | null;
  overview?: string | null;
  problem?: string | null;
  solution?: string | null;
  outcome?: string | null;
  /**
   * Bullet-point results (used for influencer campaigns).
   */
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Card image on listing pages.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Large image at the top of the case study.
   */
  heroImage?: (number | null) | Media;
  /**
   * Screenshot of results/stats shown near the outcome.
   */
  resultsImage?: (number | null) | Media;
  /**
   * Upload one or more campaign videos, or embed from YouTube/Instagram/TikTok.
   */
  videos?:
    | {
        source?: ('upload' | 'embed') | null;
        video?: (number | null) | Media;
        /**
         * YouTube / Instagram / TikTok link
         */
        embedUrl?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Case study categories. Each category gets its own page on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL identifier — leave blank to auto-generate from the title.
   */
  slug?: string | null;
  type: 'affiliate' | 'influencer';
  /**
   * Short intro shown on the category page (optional).
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and videos used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Client reviews — either an image (screenshot) or a video testimonial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewerName: string;
  /**
   * e.g. "Founder, Even Skyn" (optional)
   */
  role?: string | null;
  type: 'image' | 'video';
  rating?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Short quote shown with the review (optional).
   */
  quote?: string | null;
  /**
   * Screenshot of the review (WhatsApp, LinkedIn, email…).
   */
  image?: (number | null) | Media;
  videoSource?: ('upload' | 'embed') | null;
  video?: (number | null) | Media;
  /**
   * YouTube / Instagram / TikTok link
   */
  embedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Captured from the revenue calculator — includes what the visitor entered and what was projected.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  websiteUrl?: string | null;
  inputs?: {
    monthlyVisitors?: number | null;
    monthlyOrders?: number | null;
    averageOrderValue?: number | null;
    /**
     * %
     */
    commissionRate?: number | null;
    currency?: string | null;
    network?: string | null;
  };
  projection?: {
    projectedMonthlyRevenue?: number | null;
    projectedAnnualRevenue?: number | null;
    projectedOrders?: number | null;
    commissionCost?: number | null;
    netRevenue?: number | null;
    roas?: number | null;
    partners?: number | null;
  };
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  website?: string | null;
  service?: ('affiliate' | 'influencer' | 'both' | 'other') | null;
  budget?: ('under-1k' | '1k-3k' | '3k-10k' | '10k-plus') | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  category?: T;
  featured?: T;
  order?: T;
  client?: T;
  industry?: T;
  network?: T;
  duration?: T;
  influencer?:
    | T
    | {
        handle?: T;
        platform?: T;
        followers?: T;
        brandPartner?: T;
        brandUrl?: T;
      };
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        change?: T;
        id?: T;
      };
  overview?: T;
  problem?: T;
  solution?: T;
  outcome?: T;
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  thumbnail?: T;
  heroImage?: T;
  resultsImage?: T;
  videos?:
    | T
    | {
        source?: T;
        video?: T;
        embedUrl?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewerName?: T;
  role?: T;
  type?: T;
  rating?: T;
  featured?: T;
  order?: T;
  quote?: T;
  image?: T;
  videoSource?: T;
  video?: T;
  embedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  websiteUrl?: T;
  inputs?:
    | T
    | {
        monthlyVisitors?: T;
        monthlyOrders?: T;
        averageOrderValue?: T;
        commissionRate?: T;
        currency?: T;
        network?: T;
      };
  projection?:
    | T
    | {
        projectedMonthlyRevenue?: T;
        projectedAnnualRevenue?: T;
        projectedOrders?: T;
        commissionCost?: T;
        netRevenue?: T;
        roas?: T;
        partners?: T;
      };
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  website?: T;
  service?: T;
  budget?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}